package main.java.org.model;

import java.util.Random;

/**
 * A class for the D6 rolls generated by Dice
 *
 * @author Maysam Mokarian
 * @since 02.08.2017
 * @version 1.0
 */
public class Dice6 implements Dice{
    @Override
    public int roll() {
        return new Random().nextInt(6) + 1;
    }
}
