package main.java.org.model;

/**
 * Created by Sadra on 2/22/17.
 * STRENGTH=0, CONSTITUTION=1, DEXTERITY=2, HITPOINTS=3, LEVEL=4, ARMORCLASS=5, ATTACKBONUS=6, DAMAGEBONUS=7
 */
public enum EnhancementTypesEnum {
    STRENGTH, CONSTITUTION, DEXTERITY, HITPOINTS, LEVEL, ARMORCLASS, ATTACKBONUS, DAMAGEBONUS
}
